# INSECURE: Pod —Å hostPath volume
apiVersion: v1
kind: Pod
metadata:
  name: insecure-hostpath
  namespace: app-prod
spec:
  containers:
  - name: app
    image: nginx:latest
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /  # VIOLATION: hostPath to root
