apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: app-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: app-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: app-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-auditor
  namespace: security
