# Constraint: применить запрет hostPath к namespace audit-zone
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostPath
metadata:
  name: deny-hostpath-volumes
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces: ["audit-zone"]
