# ConstraintTemplate: запрет hostPath
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8spsphostpath
spec:
  crd:
    spec:
      names:
        kind: K8sPSPHostPath
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8spsphostpath

      violation[{"msg": msg}] {
        volume := input.review.object.spec.volumes[_]
        volume.hostPath
        msg := sprintf("hostPath volume not allowed: %v", [volume.name])
      }
