# ConstraintTemplate: требование runAsNonRoot и readOnlyRootFilesystem
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8spsprunasnonroot
spec:
  crd:
    spec:
      names:
        kind: K8sPSPRunAsNonRoot
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8spsprunasnonroot

      violation[{"msg": msg}] {
        c := input.review.object.spec.containers[_]
        not c.securityContext.runAsNonRoot == true
        msg := sprintf("Container must set runAsNonRoot: true - %v", [c.name])
      }

      violation[{"msg": msg}] {
        c := input.review.object.spec.containers[_]
        not c.securityContext.readOnlyRootFilesystem == true
        msg := sprintf("Container must set readOnlyRootFilesystem: true - %v", [c.name])
      }

      violation[{"msg": msg}] {
        c := input.review.object.spec.containers[_]
        c.securityContext.runAsUser == 0
        msg := sprintf("Container must not run as root (UID 0) - %v", [c.name])
      }
